package vaterpolo.exception;

import org.junit.Test;

public class VaterpoloExceptionTest {

	@Test
	public void konstruktor_VaterpoloException() {
		new VaterpoloException("message");
	}
}
